// This code was generated by iOS-re-lab.
// Context:
/*
%CONTEXT%
 */
Interceptor.attach(Process.getModuleByName("%MODULE%").base.add("%OFFSET%"), {
    onEnter(args) {

    },

    onLeave(retval) {

    }
});